from enum import Enum

class Evento(Enum):
    CREACION_TARJETA = "CREACION_TARJETA"
    BORRACION_TARJETA = "BORRADO DE TARJETAS"
    MOVICION_TARJETA = "MOVIMIENTOS DE TARJETAS"
    AGREGACION_USUARIO = "AGREGADO DE USUARIOS"

    INGRESO_TARJETA = "LLEGADA DE TARJETAS"
    EGRESO_TARJETA = "SALIDA DE TARJETAS"

    CAMBIO_DE_ESTADO = "CAMBIOS DE ESTADO"
    BORRADO_TARJETA = "BORRADO DE TARJETA"
