version: '3'

services:
    mysql-development:
        image: mysql:8.0.17
        environment:
            MYSQL_ROOT_PASSWORD: helloworld
            MYSQL_DATABASE: testapp
        ports:
            - "3308:3306"
            
    server:
        build: .
        command: flask run --host 0.0.0.0
        ports:
            - "4000:4000"
        volumes:
            - .:/app